// This file was auto-generated by Fern from our API Definition.

package cloud

type BootstrapResponse struct {
	Cluster BootstrapCluster  `json:"cluster,omitempty"`
	Captcha *BootstrapCaptcha `json:"captcha,omitempty"`
}
