// This file was auto-generated by Fern from our API Definition.

package cloud

import (
	rivetgo "github.com/rivet-gg/rivet-go"
)

type ValidateGroupRequest struct {
	// Represent a resource's readable display name.
	DisplayName string `json:"display_name"`
}

type ValidateGroupResponse struct {
	// A list of validation errors.
	Errors []*rivetgo.ValidationError `json:"errors,omitempty"`
}
