// This file was auto-generated by Fern from our API Definition.

package cloud

type GetRegionTiersResponse struct {
	// A list of region server tiers.
	Tiers []*RegionTier `json:"tiers,omitempty"`
}
