// This file was auto-generated by Fern from our API Definition.

package group

import (
	uuid "github.com/google/uuid"
	rivetgo "github.com/rivet-gg/rivet-go"
)

// External links for this group.
type ExternalLinks struct {
	// A link to this group's profile page.
	Profile string `json:"profile"`
}

// A group handle.
type Handle struct {
	GroupId     uuid.UUID           `json:"group_id"`
	DisplayName rivetgo.DisplayName `json:"display_name"`
	// The URL of this group's avatar image
	AvatarUrl *string        `json:"avatar_url,omitempty"`
	External  *ExternalLinks `json:"external,omitempty"`
	// Whether or not this group is a developer group.
	IsDeveloper *bool `json:"is_developer,omitempty"`
}
