// This file was auto-generated by Fern from our API Definition.

package game

import (
	uuid "github.com/google/uuid"
	rivetgo "github.com/rivet-gg/rivet-go"
	group "github.com/rivet-gg/rivet-go/common/group"
)

type Summary struct {
	GameId      uuid.UUID           `json:"game_id"`
	NameId      rivetgo.Identifier  `json:"name_id"`
	DisplayName rivetgo.DisplayName `json:"display_name"`
	// The URL of this game's logo image.
	LogoUrl *string `json:"logo_url,omitempty"`
	// The URL of this game's banner image.
	BannerUrl *string       `json:"banner_url,omitempty"`
	Url       string        `json:"url"`
	Developer *group.Handle `json:"developer,omitempty"`
	// Unsigned 32 bit integer.
	TotalPlayerCount int `json:"total_player_count"`
}
