// This file was auto-generated by Fern from our API Definition.

package api

type AccountNumber = int

// Follows regex ^(?:[^\n\r]+\n?|\n){1,5}$
type Bio = string

type DisplayName = string

// A valid email address
type Email = string

type EmptyObject struct {
}

type ErrorBody struct {
	Code          string         `json:"code"`
	Message       string         `json:"message"`
	Documentation *string        `json:"documentation,omitempty"`
	Metadata      *ErrorMetadata `json:"metadata,omitempty"`
}

// Unstructured metadata relating to an error. Must be manually parsed.
type ErrorMetadata = interface{}

// A human readable short identifier used to references resources. Different than a `uuid` because this is intended to be human readable. Different than `DisplayName` because this should not include special characters and be short.
type Identifier = string

// Documentation at https://jwt.io/
type Jwt = string

// An error given by failed content validation.
type ValidationError struct {
	// A list of strings denoting the origin of a validation error.
	Path []string `json:"path,omitempty"`
}

// A query parameter denoting the requests watch index.
type WatchQuery = *string

// Provided by watchable endpoints used in blocking loops.
type WatchResponse struct {
	// Index indicating the version of the data responded.
	// Pass this to `WatchQuery` to block and wait for the next response.
	Index string `json:"index"`
}
