// This file was auto-generated by Fern from our API Definition.

package engine

type GodotConfig struct {
}

type Html5Config struct {
}

type UnityConfig struct {
}

type UnrealConfig struct {
	// Name of the Unreal module that holds the game code.
	// This is usually the value of `$.Modules[0].Name` in the file `MyProject.unproject`.
	// _Configures Rivet CLI behavior. Has no effect on server behavior._
	GameModule string `json:"game_module"`
}

type Config struct {
	Unity  *UnityConfig  `json:"unity,omitempty"`
	Unreal *UnrealConfig `json:"unreal,omitempty"`
	Godot  *GodotConfig  `json:"godot,omitempty"`
	Html5  *Html5Config  `json:"html5,omitempty"`
}
