// This file was auto-generated by Fern from our API Definition.

package module

import (
	uuid "github.com/gofrs/uuid/v5"
	core "github.com/rivet-gg/rivet-go/core"
)

type FindLobbyRequest struct {
	Origin      *string                   `json:"-"`
	NamespaceId *core.Optional[uuid.UUID] `json:"namespace_id,omitempty"`
	Data        any                       `json:"data,omitempty"`
}
