// This file was auto-generated by Fern from our API Definition.

package captcha

// Captcha configuration.
type ConfigHcaptcha struct {
	ClientResponse string `json:"client_response"`
}

// Captcha configuration.
type ConfigTurnstile struct {
	ClientResponse string `json:"client_response"`
}
