// This file was auto-generated by Fern from our API Definition.

package captcha

// Methods to verify a captcha
type Config struct {
	Hcaptcha  *ConfigHcaptcha  `json:"hcaptcha,omitempty"`
	Turnstile *ConfigTurnstile `json:"turnstile,omitempty"`
}

// Captcha configuration.
type ConfigHcaptcha struct {
	ClientResponse string `json:"client_response"`
}

// Captcha configuration.
type ConfigTurnstile struct {
	ClientResponse string `json:"client_response"`
}
