// This file was auto-generated by Fern from our API Definition.

package devices

import (
	uuid "github.com/gofrs/uuid/v5"
	rivetgo "github.com/rivet-gg/rivet-go"
)

type GetDeviceLinkRequest struct {
	DeviceLinkToken rivetgo.Jwt        `json:"-"`
	WatchIndex      rivetgo.WatchQuery `json:"-"`
}

type GetDeviceLinkResponse struct {
	CloudToken *string                `json:"cloud_token,omitempty"`
	Watch      *rivetgo.WatchResponse `json:"watch,omitempty"`
}

type PrepareDeviceLinkResponse struct {
	DeviceLinkId    uuid.UUID `json:"device_link_id"`
	DeviceLinkToken string    `json:"device_link_token"`
	DeviceLinkUrl   string    `json:"device_link_url"`
}
