// This file was auto-generated by Fern from our API Definition.

package cdn

import (
	uuid "github.com/google/uuid"
)

// CDN configuration for a given version.
type Config struct {
	// _Configures Rivet CLI behavior. Has no effect on server behavior._
	BuildCommand *string `json:"build_command,omitempty"`
	// _Configures Rivet CLI behavior. Has no effect on server behavior._
	BuildOutput *string    `json:"build_output,omitempty"`
	SiteId      *uuid.UUID `json:"site_id,omitempty"`
	// Multiple CDN version routes.
	Routes []*Route `json:"routes,omitempty"`
}

type CustomHeadersMiddleware struct {
	Headers []*Header `json:"headers,omitempty"`
}

type Header struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type Middleware struct {
	Kind *MiddlewareKind `json:"kind,omitempty"`
}

type MiddlewareKind struct {
	CustomHeaders *CustomHeadersMiddleware `json:"custom_headers,omitempty"`
}

type Route struct {
	Glob string `json:"glob"`
	// Unsigned 32 bit integer.
	Priority int `json:"priority"`
	// Multiple CDN version middleware.
	Middlewares []*Middleware `json:"middlewares,omitempty"`
}
