// This file was auto-generated by Fern from our API Definition.

package identity

import (
	uuid "github.com/gofrs/uuid/v5"
)

// Identity configuration for a given version.
type Config struct {
	DisplayNames []string    `json:"display_names,omitempty"`
	Avatars      []uuid.UUID `json:"avatars,omitempty"`
	// **Deprecated**
	CustomDisplayNames []*CustomDisplayName `json:"custom_display_names,omitempty"`
	// **Deprecated**
	CustomAvatars []*CustomAvatar `json:"custom_avatars,omitempty"`
}

type CustomAvatar struct {
	UploadId uuid.UUID `json:"upload_id"`
}

type CustomDisplayName struct {
	DisplayName string `json:"display_name"`
}
