// This file was auto-generated by Fern from our API Definition.

package matchmaker

import (
	rivetgo "github.com/rivet-gg/rivet-go"
)

type PlayerConnectedRequest struct {
	PlayerToken string `json:"player_token"`
}

type PlayerDisconnectedRequest struct {
	PlayerToken string `json:"player_token"`
}

type GetStatisticsResponse struct {
	PlayerCount int64                                      `json:"player_count"`
	GameModes   map[rivetgo.Identifier]*GameModeStatistics `json:"game_modes,omitempty"`
}
