// This file was auto-generated by Fern from our API Definition.

package upload

// A file being prepared to upload.
type PrepareFile struct {
	// The path/filename of the file.
	Path string `json:"path"`
	// The MIME type of the file.
	ContentType *string `json:"content_type,omitempty"`
	// Unsigned 64 bit integer.
	ContentLength int64 `json:"content_length"`
}

// A presigned request used to upload files.  Upload your file to the given URL via a PUT request.
type PresignedRequest struct {
	// The name of the file to upload.  This is the same as the one given in the upload prepare file.
	Path string `json:"path"`
	// The URL of the presigned request for which to upload your file to.
	Url string `json:"url"`
}
