// This file was auto-generated by Fern from our API Definition.

package kv

import (
	uuid "github.com/gofrs/uuid/v5"
	rivetgo "github.com/rivet-gg/rivet-go"
)

type GetBatchResponse struct {
	Entries []*Entry               `json:"entries,omitempty"`
	Watch   *rivetgo.WatchResponse `json:"watch,omitempty"`
}

type GetResponse struct {
	Value Value `json:"value,omitempty"`
	// Whether or not the entry has been deleted. Only set when watching this endpoint.
	Deleted *bool                  `json:"deleted,omitempty"`
	Watch   *rivetgo.WatchResponse `json:"watch,omitempty"`
}

type PutBatchRequest struct {
	NamespaceId *uuid.UUID  `json:"namespace_id,omitempty"`
	Entries     []*PutEntry `json:"entries,omitempty"`
}

type PutRequest struct {
	NamespaceId *uuid.UUID `json:"namespace_id,omitempty"`
	Key         Key        `json:"key"`
	Value       Value      `json:"value,omitempty"`
}
