// This file was auto-generated by Fern from our API Definition.

package kv

import (
	uuid "github.com/google/uuid"
)

type DeleteOperationRequest struct {
	Key         Key        `json:"-"`
	NamespaceId *uuid.UUID `json:"-"`
}

type DeleteBatchRequest struct {
	Keys        []Key      `json:"-"`
	NamespaceId *uuid.UUID `json:"-"`
}

type GetOperationRequest struct {
	Key Key `json:"-"`
	// A query parameter denoting the requests watch index.
	WatchIndex  *string    `json:"-"`
	NamespaceId *uuid.UUID `json:"-"`
}

type GetBatchRequest struct {
	Keys []Key `json:"-"`
	// A query parameter denoting the requests watch index.
	WatchIndex  *string    `json:"-"`
	NamespaceId *uuid.UUID `json:"-"`
}

// A key-value entry.
type Entry struct {
	Key     Key   `json:"key"`
	Value   Value `json:"value,omitempty"`
	Deleted *bool `json:"deleted,omitempty"`
}

// A string representing a key in the key-value database.
// Maximum length of 512 characters.
// *Recommended Key Path Format*
// Key path components are split by a slash (e.g. `a/b/c` has the path components `["a", "b", "c"]`). Slashes can be escaped by using a backslash (e.g. `a/b\/c/d` has the path components `["a", "b/c", "d"]`).
// This format is not enforced by Rivet, but the tools built around Rivet KV work better if this format is used.
type Key = string

// A new entry to insert into the key-value database.
type PutEntry struct {
	Key   Key   `json:"key"`
	Value Value `json:"value,omitempty"`
}

// A JSON object stored in the KV database.
// A `null` value indicates the entry is deleted.
// Maximum length of 262,144 bytes when encoded.
type Value = interface{}
