// This file was auto-generated by Fern from our API Definition.

package namespaces

import (
	cloud "github.com/rivet-gg/rivet-go/cloud"
	time "time"
)

type ListNamespaceLobbiesRequest struct {
	// Returns lobbies created before this timestamp.
	BeforeCreateTs *time.Time `json:"-"`
}

type GetNamespaceLobbyResponse struct {
	Lobby   *cloud.LogsLobbySummary `json:"lobby,omitempty"`
	Metrics *cloud.SvcMetrics       `json:"metrics,omitempty"`
	// **Deprecated**
	// A list of URLs.
	StdoutPresignedUrls []string `json:"stdout_presigned_urls,omitempty"`
	// **Deprecated**
	// A list of URLs.
	StderrPresignedUrls []string `json:"stderr_presigned_urls,omitempty"`
	// **Deprecated**
	// A list of service performance summaries.
	PerfLists []*cloud.SvcPerf `json:"perf_lists,omitempty"`
}

type ListNamespaceLobbiesResponse struct {
	// A list of lobby log summaries.
	Lobbies []*cloud.LogsLobbySummary `json:"lobbies,omitempty"`
}
