// This file was auto-generated by Fern from our API Definition.

package namespaces

type GetGameNamespaceVersionHistoryRequest struct {
	// How many items to offset the search by.
	Anchor *string `json:"-"`
	// Amount of items to return. Must be between 1 and 32 inclusive.
	Limit *int `json:"-"`
}
