// This file was auto-generated by Fern from our API Definition.

package identity

import (
	rivetgo "github.com/rivet-gg/rivet-go"
)

type WatchEventsResponse struct {
	Events []*GlobalEvent         `json:"events,omitempty"`
	Watch  *rivetgo.WatchResponse `json:"watch,omitempty"`
}

type WatchEventsRequest struct {
	WatchIndex rivetgo.WatchQuery `json:"-"`
}
