// This file was auto-generated by Fern from our API Definition.

package identity

import (
	rivetgo "github.com/rivet-gg/rivet-go"
	game "github.com/rivet-gg/rivet-go/game"
	time "time"
)

type GetGameLinkRequest struct {
	IdentityLinkToken rivetgo.Jwt        `json:"-"`
	WatchIndex        rivetgo.WatchQuery `json:"-"`
}

type GetGameLinkResponse struct {
	Status          GameLinkStatus          `json:"status,omitempty"`
	Game            *game.Handle            `json:"game,omitempty"`
	CurrentIdentity *Handle                 `json:"current_identity,omitempty"`
	NewIdentity     *GetGameLinkNewIdentity `json:"new_identity,omitempty"`
	Watch           *rivetgo.WatchResponse  `json:"watch,omitempty"`
}

type PrepareGameLinkResponse struct {
	// Pass this to `GetGameLink` to get the linking status. Valid for 15 minutes.
	IdentityLinkToken string    `json:"identity_link_token"`
	IdentityLinkUrl   string    `json:"identity_link_url"`
	ExpireTs          time.Time `json:"expire_ts"`
}
