// This file was auto-generated by Fern from our API Definition.

package version

import (
	uuid "github.com/google/uuid"
	cdn "github.com/rivet-gg/rivet-go/cloud/version/cdn"
	engine "github.com/rivet-gg/rivet-go/cloud/version/engine"
	identity "github.com/rivet-gg/rivet-go/cloud/version/identity"
	kv "github.com/rivet-gg/rivet-go/cloud/version/kv"
	matchmaker "github.com/rivet-gg/rivet-go/cloud/version/matchmaker"
	time "time"
)

// Cloud configuration for a given version.
type Config struct {
	Engine     *engine.Config     `json:"engine,omitempty"`
	Cdn        *cdn.Config        `json:"cdn,omitempty"`
	Matchmaker *matchmaker.Config `json:"matchmaker,omitempty"`
	Kv         *kv.Config         `json:"kv,omitempty"`
	Identity   *identity.Config   `json:"identity,omitempty"`
}

// A full version.
type Full struct {
	VersionId uuid.UUID `json:"version_id"`
	// RFC3339 timestamp.
	CreateTs time.Time `json:"create_ts"`
	// Represent a resource's readable display name.
	DisplayName string  `json:"display_name"`
	Config      *Config `json:"config,omitempty"`
}

// A version summary.
type Summary struct {
	VersionId uuid.UUID `json:"version_id"`
	// RFC3339 timestamp.
	CreateTs time.Time `json:"create_ts"`
	// Represent a resource's readable display name.
	DisplayName string `json:"display_name"`
}
