// This file was auto-generated by Fern from our API Definition.

package client

import (
	auth "github.com/rivet-gg/rivet-go/cloud/auth"
	devicesclient "github.com/rivet-gg/rivet-go/cloud/devices/client"
	gamesclient "github.com/rivet-gg/rivet-go/cloud/games/client"
	groups "github.com/rivet-gg/rivet-go/cloud/groups"
	logs "github.com/rivet-gg/rivet-go/cloud/logs"
	tiers "github.com/rivet-gg/rivet-go/cloud/tiers"
	uploads "github.com/rivet-gg/rivet-go/cloud/uploads"
	core "github.com/rivet-gg/rivet-go/core"
	http "net/http"
)

type Client struct {
	baseURL    string
	httpClient core.HTTPClient
	header     http.Header

	Games   *gamesclient.Client
	Auth    *auth.Client
	Devices *devicesclient.Client
	Groups  *groups.Client
	Logs    *logs.Client
	Tiers   *tiers.Client
	Uploads *uploads.Client
}

func NewClient(opts ...core.ClientOption) *Client {
	options := core.NewClientOptions()
	for _, opt := range opts {
		opt(options)
	}
	return &Client{
		baseURL:    options.BaseURL,
		httpClient: options.HTTPClient,
		header:     options.ToHeader(),
		Games:      gamesclient.NewClient(opts...),
		Auth:       auth.NewClient(opts...),
		Devices:    devicesclient.NewClient(opts...),
		Groups:     groups.NewClient(opts...),
		Logs:       logs.NewClient(opts...),
		Tiers:      tiers.NewClient(opts...),
		Uploads:    uploads.NewClient(opts...),
	}
}
