// This file was auto-generated by Fern from our API Definition.

package games

import (
	uuid "github.com/gofrs/uuid/v5"
	cloud "github.com/rivet-gg/rivet-go/cloud"
	upload "github.com/rivet-gg/rivet-go/upload"
)

type ListGameCustomAvatarsResponse struct {
	// A list of custom avatar summaries.
	CustomAvatars []*cloud.CustomAvatarSummary `json:"custom_avatars,omitempty"`
}

type PrepareCustomAvatarUploadRequest struct {
	// The path/filename of the custom avatar.
	Path string `json:"path"`
	// The MIME type of the custom avatar.
	Mime *string `json:"mime,omitempty"`
	// Unsigned 64 bit integer.
	ContentLength *int64 `json:"content_length,omitempty"`
}

type PrepareCustomAvatarUploadResponse struct {
	UploadId         uuid.UUID                `json:"upload_id"`
	PresignedRequest *upload.PresignedRequest `json:"presigned_request,omitempty"`
}
