// This file was auto-generated by Fern from our API Definition.

package games

import (
	uuid "github.com/google/uuid"
	cloud "github.com/rivet-gg/rivet-go/cloud"
	upload "github.com/rivet-gg/rivet-go/upload"
)

type CreateGameCdnSiteRequest struct {
	// Represent a resource's readable display name.
	DisplayName string `json:"display_name"`
	// A list of files preparing to upload.
	Files []*upload.PrepareFile `json:"files,omitempty"`
}

type CreateGameCdnSiteResponse struct {
	SiteId            uuid.UUID                  `json:"site_id"`
	UploadId          uuid.UUID                  `json:"upload_id"`
	PresignedRequests []*upload.PresignedRequest `json:"presigned_requests,omitempty"`
}

type ListGameCdnSitesResponse struct {
	// A list of CDN site summaries.
	Sites []*cloud.CdnSiteSummary `json:"sites,omitempty"`
}
