// This file was auto-generated by Fern from our API Definition.

package games

import (
	uuid "github.com/gofrs/uuid/v5"
	time "time"
)

// A game summary.
type GameSummary struct {
	GameId uuid.UUID `json:"game_id"`
	// RFC3339 timestamp.
	CreateTs time.Time `json:"create_ts"`
	// A human readable short identifier used to references resources. Different than a `rivet.common#Uuid` because this is intended to be human readable. Different than `rivet.common#DisplayName` because this should not include special characters and be short.
	NameId string `json:"name_id"`
	// Represent a resource's readable display name.
	DisplayName      string    `json:"display_name"`
	DeveloperGroupId uuid.UUID `json:"developer_group_id"`
	// Unsigned 32 bit integer.
	TotalPlayerCount *int `json:"total_player_count,omitempty"`
	// The URL of this game's logo image.
	LogoUrl *string `json:"logo_url,omitempty"`
	// The URL of this game's banner image.
	BannerUrl *string `json:"banner_url,omitempty"`
}
