// This file was auto-generated by Fern from our API Definition.

package client

import (
	avatars "github.com/rivet-gg/rivet-go/cloud/games/avatars"
	builds "github.com/rivet-gg/rivet-go/cloud/games/builds"
	cdn "github.com/rivet-gg/rivet-go/cloud/games/cdn"
	games "github.com/rivet-gg/rivet-go/cloud/games/games"
	matchmaker "github.com/rivet-gg/rivet-go/cloud/games/matchmaker"
	namespacesclient "github.com/rivet-gg/rivet-go/cloud/games/namespaces/client"
	tokens "github.com/rivet-gg/rivet-go/cloud/games/tokens"
	versions "github.com/rivet-gg/rivet-go/cloud/games/versions"
	core "github.com/rivet-gg/rivet-go/core"
	http "net/http"
)

type Client struct {
	baseURL    string
	httpClient core.HTTPClient
	header     http.Header

	Namespaces *namespacesclient.Client
	Avatars    *avatars.Client
	Builds     *builds.Client
	Cdn        *cdn.Client
	Games      *games.Client
	Matchmaker *matchmaker.Client
	Tokens     *tokens.Client
	Versions   *versions.Client
}

func NewClient(opts ...core.ClientOption) *Client {
	options := core.NewClientOptions()
	for _, opt := range opts {
		opt(options)
	}
	return &Client{
		baseURL:    options.BaseURL,
		httpClient: options.HTTPClient,
		header:     options.ToHeader(),
		Namespaces: namespacesclient.NewClient(opts...),
		Avatars:    avatars.NewClient(opts...),
		Builds:     builds.NewClient(opts...),
		Cdn:        cdn.NewClient(opts...),
		Games:      games.NewClient(opts...),
		Matchmaker: matchmaker.NewClient(opts...),
		Tokens:     tokens.NewClient(opts...),
		Versions:   versions.NewClient(opts...),
	}
}
