// This file was auto-generated by Fern from our API Definition.

package client

import (
	links "github.com/rivet-gg/rivet-go/cloud/devices/links"
	core "github.com/rivet-gg/rivet-go/core"
	http "net/http"
)

type Client struct {
	baseURL    string
	httpClient core.HTTPClient
	header     http.Header

	Links *links.Client
}

func NewClient(opts ...core.ClientOption) *Client {
	options := core.NewClientOptions()
	for _, opt := range opts {
		opt(options)
	}
	return &Client{
		baseURL:    options.BaseURL,
		httpClient: options.HTTPClient,
		header:     options.ToHeader(),
		Links:      links.NewClient(opts...),
	}
}
